### ISSUE TITLE
Link to Sketch-file command those not work

### ISSUE THREAD

**Issue by sketch2react** [sketch2react/sketch2react-app-feedback#1]
The shortcut and the menu alternative for linking to a Sketch-file in Sketch2React v.2020.1.5 app does not work.

Drag and drop still works. 😸 👍

**Comment by freedruk** [comment]
This is caused by a change in the underlying Electron API. A fix has been implemented in the next release.

**Comment by sketch2react** [comment]
We'll release this hot-fix tonight or tomorrow 🌮 🎉

**Comment by sketch2react** [comment]
Fixed in version 2021.0.1 👍
