### ISSUE TITLE
Very Simple Portfolio.sketch

### ISSUE THREAD

**Issue by Anselmoo** [sketch2react/sketch2react-app-feedback#2]
In the case of `Very Simple Portfolio.sketch` the html-export only, exports:

1. index.html
2. dude1.html
3. buriseoftheendermen.html

Furthermore, only the first link to `buriseoftheendermen.html` is working, and cannot continue to `dude1.html`.
The rendering in Sketch2React 2021.2.1 works fine instead.

Thx for feedback

**Comment by juanofteamsketch2react** [comment]
Hey! Thanks for the feedback, we'll definitely look into it. Make always sure you visit each page once in S2R and wait for the message "added to the export bundle" or it doesn't get added to export.

**Comment by Anselmoo** [comment]
> Hey! Thanks for the feedback, we'll definitely look into it. Make always sure you visit each page once in S2R and wait for the message "added to the export bundle" or it doesn't get added to export.

Thx for quick feedback! That was the issue

**Comment by juanofteamsketch2react** [comment]
@Anselmoo You're welcome 😸 
We really need to improve the user experience of adding things to export, I have a few ideas. Also thinking about adding this as a rule to our Sketch assistant, so you're always reminded directly inside Sketch 💎
